services:
    mirotalksfu:
        image: mirotalk/sfu:latest
        container_name: mirotalksfu
        hostname: mirotalksfu
        restart: unless-stopped
        volumes:
            - ./app/src/config.js:/src/app/src/config.js:ro
            - ./.env:/src/.env:ro
            # Mandatory volume if `server.recording.enabled` is true in app/src/config.js
            # - ./app/rec:/src/app/rec
            # Mandatory volume if `server.rtmp.enabled.fromFile` is true in app/src/config.js
            # - ./app/rtmp:/src/app/rtmp
            # Optional volumes for real-time updates:
            # - ./app/:/src/app/:ro
            # - ./public/:/src/public/:ro
        ports:
            - '3010:3010/tcp'
            - '40000-40100:40000-40100/tcp'
            - '40000-40100:40000-40100/udp'
